[package]
name = "customer-server"
license = "BUSL-1.1"
edition = "2024"

[features]

fail-on-warnings = []

[dependencies]
lana-app = { workspace = true }

tracing-utils = { workspace = true, features = ["http"] }
jwks-utils = { workspace = true }

es-entity = { workspace = true, features = ["graphql"] }

serde = { workspace = true }
url = { workspace = true }
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
