[files]
extend-exclude = [
	"CHANGELOG.md",
	"jwks.json",
	"dev/fake-service-account.json",
	"**/pnpm-lock.yaml",
	"/apps/admin-panel/lib/graphql/generated/mocks.ts",
	"/apps/admin-panel/messages/es.json",
	"/apps/admin-panel/cypress/manuals/*",
	"dev/keycloak/internal-realm.json",
	"dev/keycloak/customer-realm.json",
	"docs/mermaid-init.js",
	"docs/mermaid.min.js"
]
