[package]
name = "core-price"
license = "BUSL-1.1"
edition = "2024"

[features]

fail-on-warnings = []
json-schema = ["dep:schemars", "core-money/json-schema"]

[dependencies]
core-money = { workspace = true }

anyhow = { workspace = true }
cached = { workspace = true }
job = { workspace = true }
outbox = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
schemars = { workspace = true, optional = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
