[package]
name = "lana-credit-ledger"
license = "BUSL-1.1"
edition = "2024"

[package.metadata.cargo-machete]
ignored = ["tracing-utils"]

[features]
fail-on-warnings = []

[dependencies]
core-credit = { workspace = true }
core-credit-collection = { workspace = true }
core-accounting = { workspace = true }
cala-ledger = { workspace = true }
money = { workspace = true }
audit = { workspace = true }
es-entity = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
tracing = { workspace = true }
tracing-macros = { workspace = true }
tracing-utils = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
