[package]
name = "admin-graphql-audit"
license = "BUSL-1.1"
edition = "2024"

[dependencies]
lana-app = { workspace = true }
audit = { workspace = true }
admin-graphql-access = { workspace = true }
admin-graphql-shared = { path = "../admin-graphql-shared" }
async-graphql = { workspace = true }
es-entity = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
