[package]
name = "domain-config"
edition = "2024"
license = "BUSL-1.1"

[features]
fail-on-warnings = []

[dependencies]
chrono = { workspace = true }
es-entity = { workspace = true }
serde = { workspace = true, features = ["derive"] }
derive_builder = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-utils = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
