[package]
name = "domain-config"
edition = "2024"
license = "BUSL-1.1"

[features]
fail-on-warnings = []
json-schema = ["dep:schemars", "es-entity/json-schema"]

[dependencies]
es-entity = { workspace = true }
serde = { workspace = true, features = ["derive"] }
derive_builder = { workspace = true }
serde_json = { workspace = true }
inventory = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-macros = { workspace = true }
tracing-utils = { workspace = true }
rust_decimal = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
schemars = { workspace = true, optional = true }

[dev-dependencies]
rust_decimal_macros = { workspace = true }
