[package]
name = "core-credit-collection"
license = "BUSL-1.1"
edition = "2024"

[features]
fail-on-warnings = []
graphql = ["es-entity/graphql", "cala-ledger-core-types/graphql"]
json-schema = [
    "dep:schemars",
    "es-entity/json-schema",
    "money/json-schema",
    "job/json-schema",
    "cala-ledger-core-types/json-schema",
]

[dependencies]
money = { workspace = true }
permission-sets-macro = { workspace = true }
core-credit-terms = { path = "../terms" }

audit = { workspace = true }
authz = { workspace = true }
obix = { workspace = true }
job = { workspace = true }

cala-ledger-core-types = { workspace = true }
es-entity = { workspace = true }
sqlx = { workspace = true }

strum = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-macros = { workspace = true }
tracing-utils = { workspace = true }
derive_builder = { workspace = true }
async-trait = { workspace = true }
schemars = { workspace = true, optional = true }
workspace-hack = { version = "0.1", path = "../../../workspace-hack" }

[dev-dependencies]
anyhow = { workspace = true }
authz = { workspace = true, features = ["test-dummy"] }
cala-ledger = { workspace = true }
lana-collection-ledger = { workspace = true }
obix = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true }
