[package]
name = "custom-lints"
version = "0.1.0"
license = "BUSL-1.1"
edition = "2024"

[dependencies]
syn = { version = "2", features = ["full", "visit"] }
walkdir = "2"
rayon = "1"
cargo_metadata = "0.23"
anyhow = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
