[package]
name = "admin-graphql-accounting"
license = "BUSL-1.1"
edition = "2024"

[dependencies]
lana-app = { workspace = true }
admin-graphql-shared = { path = "../admin-graphql-shared" }
async-graphql = { workspace = true }
es-entity = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }
obix = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["es-entity"]
