[package]
name = "admin-graphql-accounting"
license = "BUSL-1.1"
edition = "2024"

[dependencies]
lana-app = { workspace = true }
admin-graphql-shared = { path = "../admin-graphql-shared" }
es-entity = { workspace = true }
async-graphql = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
