[package]
name = "core-credit-disbursal"
license = "BUSL-1.1"
edition = "2024"

[features]
fail-on-warnings = []
graphql = ["dep:async-graphql", "es-entity/graphql", "cala-ledger/graphql"]
json-schema = [
    "dep:schemars",
    "es-entity/json-schema",
    "core-money/json-schema",
    "core-credit-terms/json-schema",
    "job/json-schema",
    "cala-ledger/json-schema",
    "public-id/json-schema",
]

[dependencies]
core-money = { workspace = true }
core-accounting = { workspace = true }
core-credit-terms = { path = "../terms" }
core-credit-collection = { path = "../collection" }
governance = { workspace = true }

audit = { workspace = true }
authz = { workspace = true }
obix = { workspace = true }
job = { workspace = true }
public-id = { workspace = true }

cala-ledger = { workspace = true }
es-entity = { workspace = true }
sqlx = { workspace = true }

strum = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-macros = { workspace = true }
tracing-utils = { workspace = true }
uuid = { workspace = true }
derive_builder = { workspace = true }
rust_decimal = { workspace = true }
async-trait = { workspace = true }
schemars = { workspace = true, optional = true }
async-graphql = { workspace = true, optional = true }
workspace-hack = { version = "0.1", path = "../../../workspace-hack" }
