[package]
name = "admin-graphql-credit"
license = "BUSL-1.1"
edition = "2024"

[dependencies]
lana-app = { workspace = true }
admin-graphql-shared = { path = "../admin-graphql-shared" }
admin-graphql-accounting = { path = "../admin-graphql-accounting" }
admin-graphql-custody = { path = "../admin-graphql-custody" }
admin-graphql-governance = { path = "../admin-graphql-governance" }

es-entity = { workspace = true }
async-graphql = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["es-entity"]
