[package]
name = "admin-graphql-price"
license = "BUSL-1.1"
edition = "2024"

[dependencies]
lana-app = { workspace = true }
async-graphql = { workspace = true }
futures = { workspace = true }
obix = { workspace = true }
