[package]
name = "core-time-events"
license = "BUSL-1.1"
edition = "2024"

[features]
fail-on-warnings = []

[dependencies]
outbox = { workspace = true }
job = { workspace = true }

sqlx = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }

