[package]
name = "core-time-events"
edition = "2024"

[dependencies]
domain-config = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

sim-time = { workspace = true, optional = true }

[lints]
workspace = true
