[package]
name = "core-credit-terms"
license = "BUSL-1.1"
edition = "2024"

[features]

fail-on-warnings = []
graphql = [ "dep:async-graphql"]
json-schema = ["dep:schemars", "es-entity/json-schema", "core-money/json-schema", "core-price/json-schema"]

[dependencies]
core-money = { workspace = true }
core-price = { workspace = true }

strum = { workspace = true }
thiserror = { workspace = true }
derive_builder = { workspace = true }
es-entity = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
async-graphql = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
