[package]
name = "core-credit-terms"
license = "BUSL-1.1"
edition = "2024"

[features]

fail-on-warnings = []
graphql = [ "dep:async-graphql"]
json-schema = ["dep:schemars", "es-entity/json-schema", "money/json-schema", "core-price/json-schema"]

[dependencies]
money = { workspace = true }
core-price = { workspace = true }

audit = { workspace = true }
authz = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
derive_builder = { workspace = true }
es-entity = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
tracing-macros = { workspace = true }
tracing-utils = { workspace = true }
async-graphql = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
workspace-hack = { version = "0.1", path = "../../../workspace-hack" }
