[package]
name = "contract-creation"
license = "BUSL-1.1"
edition = "2024"

[package.metadata.cargo-machete]
ignored = ["schemars"]

[features]
fail-on-warnings = []
json-schema = ["dep:schemars", "es-entity/json-schema", "audit/json-schema"]

[dependencies]
core-customer = { workspace = true }
core-applicant = { workspace = true }
document-storage = { workspace = true }
job = { version = "0.5.1" }
obix = { workspace = true }
authz = { workspace = true }
audit = { workspace = true }
rendering = { workspace = true }

# External dependencies
es-entity = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
handlebars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-macros = { workspace = true }
tracing-utils = { workspace = true }
uuid = { workspace = true }
strum = { workspace = true }

schemars = { workspace = true, optional = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
