[package]
name = "deposit-sync"
license = "BUSL-1.1"
edition = "2024"

[features]
fail-on-warnings = []

[dependencies]

core-deposit = { workspace = true }
core-customer = { workspace = true }
money = { workspace = true }
governance = { workspace = true }

sumsub = { workspace = true }
es-entity = { workspace = true }
obix = { workspace = true }
job = { workspace = true }
audit = { workspace = true }
authz = { workspace = true }

lana-events = { workspace = true }

tracing = { workspace = true }
tracing-macros = { workspace = true }
tracing-utils = { workspace = true }
thiserror = { workspace = true }
rust_decimal = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
