[package]
name = "customer-sync"
license = "BUSL-1.1"
edition = "2024"

[features]
fail-on-warnings = []

[dependencies]

core-customer = { workspace = true }
core-deposit = { workspace = true }
governance = { workspace = true }

obix = { workspace = true }
job = { workspace = true }
audit = { workspace = true }
authz = { workspace = true }

tracing = { workspace = true }
tracing-macros = { workspace = true }
tracing-utils = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
keycloak-client = { workspace = true }
chrono = { workspace = true }
sim-time = { workspace = true, optional = true }
lana-events = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
