[package]
name = "customer-sync"
license = "BUSL-1.1"
edition = "2024"

[features]
fail-on-warnings = []

[dependencies]

core-customer = { workspace = true }
core-deposit = { workspace = true }
core-time-events = { workspace = true }
governance = { workspace = true }

es-entity = { workspace = true }
obix = { workspace = true }
job = { workspace = true }
audit = { workspace = true }
authz = { workspace = true }

tracing = { workspace = true }
tracing-macros = { workspace = true }
tracing-utils = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
keycloak-client = { workspace = true }
lana-events = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
authz = { workspace = true, features = ["test-dummy"] }
obix = { workspace = true, features = ["test-utils"] }
core-customer = { workspace = true }
core-time-events = { workspace = true }
core-deposit = { workspace = true }
governance = { workspace = true }
lana-events = { workspace = true }
cloud-storage = { workspace = true }
document-storage = { workspace = true }
public-id = { workspace = true }
job = { workspace = true }
es-entity = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
strum = { workspace = true }
chrono-tz = { workspace = true }
