[package]
name = "lana-events"

license = "BUSL-1.1"
edition = "2024"

[features]

fail-on-warnings = []

[dependencies]
governance = { workspace = true }
core-access = { workspace = true }
core-custody = { workspace = true }
core-customer = { workspace = true }
core-credit = { workspace = true }
core-deposit = { workspace = true }
core-report = { workspace = true }
core-price = { workspace = true }
obix = { workspace = true }

serde = { workspace = true }
strum = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
