[package]
name = "lana-events"

license = "BUSL-1.1"
edition = "2024"

[features]
fail-on-warnings = []
json-schema = [
    "dep:schemars",
    "governance/json-schema",
    "core-access/json-schema",
    "core-accounting/json-schema",
    "core-custody/json-schema",
    "core-customer/json-schema",
    "core-credit/json-schema",
    "core-credit-collection/json-schema",
    "core-deposit/json-schema",
    "core-report/json-schema",
    "core-price/json-schema",
    "core-time-events/json-schema",
]

[dependencies]
governance = { workspace = true }
core-access = { workspace = true }
core-accounting = { workspace = true }
core-custody = { workspace = true }
core-customer = { workspace = true }
core-credit = { workspace = true }
core-credit-collection = { workspace = true }
core-deposit = { workspace = true }
core-report = { workspace = true }
core-price = { workspace = true }
core-time-events = { workspace = true }
obix = { workspace = true }

serde = { workspace = true }
strum = { workspace = true }
schemars = { workspace = true, optional = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
