[package]
name = "core-fcredit-facility"
license = "BUSL-1.1"
edition = "2024"

[features]

fail-on-warnings = []
json-schema = ["dep:schemars", "cala-ledger/json-schema", "es-entity/json-schema", "core-money/json-schema", "job/json-schema", "core-price/json-schema", "outbox/json-schema", "public-id/json-schema"]

[dependencies]
outbox = { workspace = true }
core-money = { workspace = true }
core-price = { workspace = true }
core-custody = { workspace = true }
core-customer = { workspace = true }
audit = { workspace = true }
governance = { workspace = true }
authz = { workspace = true }
public-id = { workspace = true }
credit-terms = { package = "core-fcredit-terms", path = "../terms" }

tracing = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
strum = { workspace = true }
derive_builder = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
cala-ledger = { workspace = true }
es-entity = { workspace = true }
sqlx = { workspace = true }
job = { workspace = true }

schemars = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
