[package]
name = "admin-graphql-shared"
license = "BUSL-1.1"
edition = "2024"

[dependencies]
lana-app = { workspace = true }
audit = { workspace = true }
domain-config = { workspace = true }

es-entity = { workspace = true, features = ["graphql"] }

async-graphql = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
