[package]
name = "lanacli"
version = "0.1.0"
license = "BUSL-1.1"
edition = "2024"

[features]
fail-on-warnings = []

[[bin]]
name = "lanacli"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
graphql_client = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
comfy-table = { workspace = true }
url = { workspace = true }
